### ISSUE TITLE
Error: GraphQL conflict for 'e' detected! Multiple versions of graphql exist in your node_modules?

### ISSUE THREAD

**Issue by speller** [graphile/postgraphile-lambda-example#14]
Hello,

After manual installation of the Lambda function I see the following error in the CloudWatch logs:

> 
> 22:06:44
> START RequestId: f6f75d3d-a0a6-4d68-9a59-bcbb5c5e06d6 Version: 1
> 
> 22:06:47
> END RequestId: f6f75d3d-a0a6-4d68-9a59-bcbb5c5e06d6
> 
> 22:06:47
> REPORT RequestId: f6f75d3d-a0a6-4d68-9a59-bcbb5c5e06d6	Duration: 3003.14 ms	Billed Duration: 3000 ms Memory Size: 128 MB	Max Memory Used: 42 MB
> 
> 22:06:47
> 2019-05-22T13:06:47.380Z f6f75d3d-a0a6-4d68-9a59-bcbb5c5e06d6 Task timed out after 3.00 seconds
> 
> 22:06:47
> A fatal error occurred when building the initial schema, so the process will now exit. Error details:
> 
> 22:06:47
> Error: GraphQL conflict for 'e' detected! Multiple versions of graphql exist in your node_modules?
> 
> 22:06:47
> at Object.newWithHooks (/var/task/index.js:142:82538)
> 
> 22:06:47
> at /var/task/index.js:142:130002
> 
> 22:06:47
> at t.default.applyHooks (/var/task/index.js:142:72919)
> 
> 22:06:47
> at t.default.createBuild (/var/task/index.js:142:73808)
> 
> 22:06:47
> at t.default.buildSchema (/var/task/index.js:142:73899)
> 
> 22:06:47
> at Object.t.createPostGraphileSchema (/var/task/index.js:13:6063)

What I'm doing wrong?

**Comment by benjie** [comment]
That could be one of two things:

1. there are multiple versions of `graphql` in your node_modules folder; this should not be the case if you are using `yarn`
2. you've enabled minification as part of your webpack build, and it has resulted in GraphQL becoming corrupted such that it cannot perform its regular check; make sure you use DefinePlugin to define `NODE_ENV = "production"`

**Comment by speller** [comment]
1. No multiple versions of GraphQL. Yarn is used.
2. I've turned off the uglifyjs plugin and tried development mode to skip all the webpack optimizations. Same result.

But I don't remember what I did but after some manupulations the error

**Comment by lucasrrt** [comment]
@speller How did you solve this?
