### ISSUE TITLE
makeCache hangs/fails on node v14.7.0

### ISSUE THREAD

**Issue by micimize** [graphile/postgraphile-lambda-example#23]
I use an near-identical setup for generating the cache, and after coming back to my project and updating node to `14.7.0` and postgraphile to `4.7.0` the script now exits without writing the cache. I tried some [top level promise await hacks](https://stackoverflow.com/a/23354058/2234013) but the process just hangs on `await createPostGraphileSchema`

For now as a workaround I'm just passing `writeCache` to `postgraphile` in dev mode which still works fine (and runs quickly).

```javascript
// This script is called from scripts/generate-cache
const { createPostGraphileSchema } = require('postgraphile');
const { options } = require('./postgraphileOptions');
const { Pool } = require('pg');

const schemas = process.env.DATABASE_SCHEMAS
  ? process.env.DATABASE_SCHEMAS.split(',')
  : ['app_public'];

async function main() {
  const pgPool = new Pool({
    connectionString: process.env.DATABASE_URL,
  });
  console.log('will be logged');
  await createPostGraphileSchema(pgPool, schemas, {
    ...options,
    writeCache: `${__dirname}/../dist/postgraphile.cache`,
  });
  console.log('will not be logged before process terminates');
  await pgPool.end();
}

main().then(null, e => {
  // eslint-disable-next-line no-console
  console.error(e);
  process.exit(1);
});
```

**Comment by benjie** [comment]
This most likely is a compatibility issue between node 14 and the pg module. Please upgrade pg and report back 👍

**Comment by micimize** [comment]
right you are!
